# Generated by Django 3.2.8 on 2021-10-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_id'),
        ('images', '0002_image_total_likes'),
    ]

    operations = [
    ]
